### ISSUE TITLE
Document minimum supported rust version

### ISSUE THREAD

**Issue by snsmac** [brycx/orion#104]
It could be useful to specify a minimum required rust version and add an CI test to enforce this.
Note: zeroize 1.0 requires rustc 1.36 or newer

**Comment by brycx** [comment]
I agree this would be nice to have, instead of only supporting the latest stable Rust version. It would help users check whether it's possible for them to use orion on their platform.

This will however mean that future updates that bump MSRV will be breaking. This is currently not strictly the case, because orion only supports latest Rust stable. I won't hesitate to bump MSRV at any point though, if it improves the library. So pinning a MSRV will serve purely as an informational/documentation improvement.

>  Note: zeroize 1.0 requires rustc 1.36 or newer

Yup, I'm pretty sure MSRV would be 1.36 at this point.

**Comment by brycx** [comment]
I've seen multiple crates, including zeroize, stating that a bump in MSRV is not considered a breaking change on their part. It's not a part of the [API evolution RFC](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md) either, so we can take the same approach to this.
