### ISSUE TITLE
Add support for new password hashing algorithm

### ISSUE THREAD

**Issue by brycx** [brycx/orion#109]
Currently the only password hashing algorithm supported is PBKDF2. This is a dated algorithm and better alternatives exist.

The high-level API in `orion::pwhash` offers key derivation using PBKDF2, but should preferably use a more modern algorithm.

Argon2i would be a very good replacement, which is also provided by other crypto libraries such as libsodium. I know @vlmutolo began some work on implementing this. 

To provide Argon2i and keep unsafe code at a minimum, this should for starters not support threading. Alternatively we could provide scrypt, though a PBKDF2-SHA256 implementation is missing for this. I don't see an argument for providing scrypt rather than Argon2i however.

**Comment by finfet** [comment]
I'd like to second choosing argon2i. Perhaps it can be based off of [rust-argon2](https://github.com/sru-systems/rust-argon2) but use orion's blake2b implementation.

**Comment by brycx** [comment]
> Perhaps it can be based off of rust-argon2 but use orion's blake2b implementation.

Yeah, I've been looking at those as well. It's nice to already have the BLAKE2b permutation required. @finfet Would you be interested in implementing this?

**Comment by finfet** [comment]
@brycx Sure, I can give it a shot this weekend.

**Comment by brycx** [comment]
@finfet Sounds great!

**Comment by finfet** [comment]
I spent a few hours poking around at an Argon2 implementation this weekend. I like the implementation of `rust-argon2`. It is mostly a re-implementation of the original C reference code. However, it doesn't use constant time comparisons which makes me a little bit skeptical of its quality.

The `golang.org/x/crypto/argon2` implementation was also pretty easy to read as a reference.

It looks like openssl and therefore Python are unlikely to implement Argon2 because of the threading requirements. I'm not sure if there are any security implementations due to not using threading, but I assume it's fine because the Java BouncyCastle implementation doesn't use threads. My guess is that it's probably just slower to compute the hash because each round can't be computed in parallel.

Overall though, I'm still pretty new to rust so a full argon2 implementation is likely beyond my capabilities at this time.

**Comment by brycx** [comment]
I've also been looking at the Go implementation. There is also the [argon2rs crate](https://github.com/bryant/argon2rs) to look at for reference points.

> My guess is that it's probably just slower to compute the hash because each round can't be computed in parallel.

AFAIU there is no security impact of not supporting multiple threads.

> Overall though, I'm still pretty new to rust so a full argon2 implementation is likely beyond my capabilities at this time.

That's totally fair. I appreciate you looking into this, thanks!
