### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by garbageslam** [brycx/orion#125]
In this PR it is written: https://github.com/brycx/orion/pull/113

> Edit: I haven't been able to get a solution working, that doesn't require heap allocation. Thus, the Argon2i implementation will not be available with no_std.

In modern stable versions of rust, you can use `#![no_std]` and `extern crate alloc;` to get the stable alloc crate, without pulling in threading mutexes and all that. This makes the crate a lot more portable to embedded devices, microcontrollers, sgx enclaves, etc. This is the configuration in which most rust cryptographic crates try to build, if they cannot build without an allocator.

**Comment by brycx** [comment]
The `alloc` crate was also something I looked into when #113 was being implemented. The main reason for not using it was, that I wanted to keep the feature-configuration as simple as possible and I didn't have a `no-std` with `alloc` use case myself.

I'm willing to look into having Argon2i in the `hazardous` module use `alloc` instead of `std` (which would likely be feature-gated). I wasn't sure whether this was a feature-request or a question about why it wasn't implemented in the first place.

**Comment by garbageslam** [comment]
i guess its a feature request. thanks for explaining!
