### ISSUE TITLE
Consider calculating expected_tag internally in auth::authenticate_verify

### ISSUE THREAD

**Issue by vlmutolo** [brycx/orion#157]
Here's the current API for `orion::hash::authenticate_verify` (taken straight from the current docs).

```rust
use orion::auth;

let key = auth::SecretKey::default();
let msg = "Some message.".as_bytes();
let expected_tag = auth::authenticate(&key, msg)?;
assert!(auth::authenticate_verify(&expected_tag, &key, &msg).is_ok());
```

This API is good as it is, but I think it could be even easier. I would propose performing `auth::authenticate` in the body of `auth::authenticate_verify`. This is similar to the issue I raised in #138. I imagine anyone using this function will have to start by calculating the expected tag, and then passing it in. We can save users this step with the following proposed API. 

```rust
use orion::auth;

let key = auth::SecretKey::default();
let msg = "Some message.".as_bytes();
assert!(auth::authenticate_verify(&key, &msg).is_ok());
```

I don't actually have a use case for the `auth` module yet. I was just looking through the docs and wondered why we have to calculate the `expected_key` ourselves.

I'd be happy to work on this PR myself if it's a direction we want to go. Just thought I'd actually start the process the right way this time with a issue before PR. 😅

**Comment by brycx** [comment]
Thanks for this detailed description! Just like last time, it's a pleasure to receive these issues.

> This API is good as it is, but I think it could be even easier. I would propose performing auth::authenticate in the body of auth::authenticate_verify

As much as I'd love to simplify the APIs, this is a change we cannot make. If we perform the tag calculation of the expected tag, within the verification function, then `authenticate_verify()` would never fail. In the above proposal, the key and message stay the same, so calculating the tag twice, with the same parameters, will always give the same two tags. A user must provide the expected tag, because this function evaluates whether a given key and message produce an expected tag.

In terms of #138, it's also somewhat different. There, we take the parameters used to hash the password, but the user still needs to provide the expected password hash. If we run the password hash twice, in `pwhash::hash_password_verify()`, then it would always return true due to the same logic described above. The parameters used in `pwhash` you've proposed to elide from the API, would be the equivalent to the constant output size for the tags, produced by `orion::auth::authenticate()`: 

https://github.com/brycx/orion/blob/7ee5bb95bb263dd842bb87402e7c7088f34b23ec/src/high_level/auth.rs#L78


I hope this clears up why we can't make this change. I'll close the issue for now, but please let me know, or re-open the issue, if there's something I've misunderstood.

**Comment by vlmutolo** [comment]
Yes, this does clear it up. I stared at the example above for five minutes before I understood what was tripping me up. I think maybe changing the variable names in the example would help. I saw “expected_tag” and thought it was something that the developer would compute and not the external party. 

Or maybe just splitting up the lines with two comments like this. 

```
use orion::auth;

// unauthenticated source generates message and authentication tag
let key = auth::SecretKey::default();
let msg = "Some message.".as_bytes();
let expected_tag = auth::authenticate(&key, msg)?;

// verify the authenticity of the tag
assert!(auth::authenticate_verify(&expected_tag, &key, &msg).is_ok());
```

**Comment by brycx** [comment]
I don't know what other name than "expected" would help. The example also uses this name, since `authenticate_verify()` takes `expected: &Tag`.

But the change to the example seems like a good way to explain it more clearly. Regardless of the variable name, the example should be updated. I'll make a follow-up issue.

**Comment by vlmutolo** [comment]
Yeah after I looked at it again, the variable names are fine. I was just confused about the source of each of the variables, which is tough to represent in a small docs example. But I think something like the amended  version with comments would help. And yes, it should probably be a new issue.
