### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ritalinn** [brycx/orion#16]
Hi, sir. I like to help open source projects. I have an idea for you. Do you want me to design a logo?

**Comment by ritalinn** [comment]
I designed a simple and strong logo for you. what do you think? What is your decision?

![orion](https://user-images.githubusercontent.com/41344739/43895575-789b0a96-9bde-11e8-8fb5-85c521984b19.jpg)

**Comment by brycx** [comment]
I'm not really a fan of the orange/reddish and green colours, but the blue is really good 👍 Since orion is a constellation, I'd like to see this represented in the logo. I saw your design for [Libelection](https://github.com/quiqupltd/libelection), and like the idea of substituting the first letter with a logo animation. So substituting the "O" with an animation. 

In terms of animation, I like your simple approach, could you make an "O" with something that represents a constellation in the likes of this and keep that blue colour (but of course not exactly this)?:

![const](https://cdn.dribbble.com/users/5976/screenshots/2921603/c_for_constellation__logo_design_symbol_by_alex_tass.jpg)

And then "rion" after that animation. I hope that's not too much to ask for.

**Comment by ritalinn** [comment]
I designed a minimalist logo in the direction of your wishes. What is your decision ?
![orion](https://user-images.githubusercontent.com/41344739/43909766-cae61ca8-9c03-11e8-8804-c1dd8c5d4917.jpg)

**Comment by brycx** [comment]
Nice work. I like the last one best, let's use that one.

**Comment by ritalinn** [comment]
Thank you for liking the design. I sent pr. I sent the files.

**Comment by brycx** [comment]
Merged in #17.
