### ISSUE TITLE
Unecessary #[must_use]

### ISSUE THREAD

**Issue by snsmac** [brycx/orion#89]
Many functions that return a Result are tagged with #[must_use].
This seems unnecessary, because Result itself is already tagged with it https://doc.rust-lang.org/std/result/#results-must-be-used

**Comment by brycx** [comment]
Thank you for pointing this out. The reason `#[must_use]` on `Result` is still in the code-base is, that I thought about adding an explicit security-warning to these. Such that a user is warned that ignoring results may have a negative effect on security. But, as you can see, I haven't gotten any further with the idea. 

I have opened an [issue](https://github.com/brycx/orion/issues/90) where this can be discussed further, but until anything has been decided there is no reason for `#[must_use]` on `Result`. If you have any opinions on adding security-warnings, please feel free to share them in the linked issue. Otherwise, if you want, I'd gladly welcome a PR to remove the `#[must_use]` until next steps have been decided. Or you could wait a bit, in case the decision is quickly made and then add the security-warnings.
